"""CrewAI tools for RCM workflows."""

from rcm_agent.tools._types import (
    AppealPacket,
    AuthPacket,
    AuthStatusResult,
    AuthSubmitResult,
    BenefitsResult,
    ClinicalIndicatorsResult,
    CoordinationOfBenefitsResult,
    DenialAnalysis,
    DenialSummary,
    EligibilityResult,
    InvalidPair,
    MissingChargesResult,
    ModifierSuggestion,
    PerCodeReimbursement,
    ProcedureBenefit,
    ReimbursementResult,
    SuggestCodesResult,
    SuggestedCode,
    ValidateCodesResult,
)
from rcm_agent.tools.appeal import (
    assemble_appeal_packet,
    generate_appeal_letter,
    search_payer_policies_for_appeal,
)
from rcm_agent.tools.coding import (
    calculate_expected_reimbursement,
    identify_missing_charges,
    search_coding_guidelines,
    search_cms_requirements,
    search_ncci_edits,
    suggest_codes,
    validate_code_combinations,
)
from rcm_agent.tools.denial import (
    DENIAL_REASON_CODE_CATALOG,
    DenialType,
    assess_appeal_viability,
    classify_denial_type,
    parse_denial_reason_codes,
)
from rcm_agent.tools.eligibility import (
    check_coordination_of_benefits,
    check_member_eligibility,
    flag_coverage_gaps,
    verify_benefits,
)
from rcm_agent.tools.logic import check_escalation
from rcm_agent.tools.prior_auth import (
    assemble_auth_packet,
    extract_clinical_indicators,
    poll_auth_status,
    search_payer_policies,
    submit_auth_request,
)

__all__ = [
    # TypedDict types
    "AppealPacket",
    "AuthPacket",
    "AuthStatusResult",
    "AuthSubmitResult",
    "BenefitsResult",
    "ClinicalIndicatorsResult",
    "CoordinationOfBenefitsResult",
    "DenialAnalysis",
    "DenialSummary",
    "EligibilityResult",
    "InvalidPair",
    "MissingChargesResult",
    "ModifierSuggestion",
    "PerCodeReimbursement",
    "ProcedureBenefit",
    "ReimbursementResult",
    "SuggestCodesResult",
    "SuggestedCode",
    "ValidateCodesResult",
    # Functions
    "assemble_appeal_packet",
    "assess_appeal_viability",
    "calculate_expected_reimbursement",
    "check_coordination_of_benefits",
    "check_escalation",
    "check_member_eligibility",
    "classify_denial_type",
    "DENIAL_REASON_CODE_CATALOG",
    "DenialType",
    "extract_clinical_indicators",
    "flag_coverage_gaps",
    "generate_appeal_letter",
    "identify_missing_charges",
    "parse_denial_reason_codes",
    "poll_auth_status",
    "search_cms_requirements",
    "search_coding_guidelines",
    "search_ncci_edits",
    "search_payer_policies_for_appeal",
    "search_payer_policies",
    "submit_auth_request",
    "suggest_codes",
    "validate_code_combinations",
    "verify_benefits",
]
